<?php
/**
 * 单元测试类
 */

namespace demo\tests;
use demo\service\UserService;
use herosphp\bean\Beans;
use herosphp\http\HttpClient;

class DemoServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserService
     */
    protected $service;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this ->service = Beans::get("demo.user.service");
    }

    /**
     * @test
     */
    public function hello() {
        $this->service->hello();
    }

    /**
     * @test
     */
    public function httpclient() {

        $result = HttpClient::delete('http://api.herosphp.my/shops/11111',
            json_encode(array("username" => 'xxxxxx', "password" => "11111111")));
        print_r($result);
    }

}
