<?php
/**
 * 单元测试类
 */

namespace demo\tests;
use demo\service\UserService;
use herosphp\bean\Beans;
class UserServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserService
     */
    protected $service;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this ->service = Beans::get("demo.user.service");
    }

    /**
     * @test
     */
    public function hello() {
        $this->service->hello();
    }

}
